### ISSUE TITLE
运行后报错，报缺少文件question_classification.txt

### ISSUE THREAD

**Issue by lisl2017** [kobeyk/Spring-Boot-Neo4j-Movies#3]
项目运行后，输入 后发送，报错，
错误如下
java.io.FileNotFoundException: D:\git\project\Spring-Boot-Neo4j-Movies\data\question\question_classification.txt (系统找不到指定的路径。)

通过您博客第四步https://blog.csdn.net/Appleyk/article/details/80335536 中提到的https://github.com/hankcs/HanLP/releases 下载的data 压缩包里面没有question_classification.txt文件

请问该文件是如何生成的尼

**Comment by lisl2017** [comment]
忽略如上问题，谢谢

**Comment by zhaozih** [comment]
请问该文件是如何生成的呢？
